version: '2'
services:
    mygateway0222-app:
        image: mygateway0222
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
           # - SPRING_DATASOURCE_URL=jdbc:mysql://mygateway0222-mysql:3306/mygateway0222?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATASOURCE_URL=jdbc:mysql://myuaa02-mysql:3306/myuaa02?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
        ports:
            - 8091:8091

